package com.lider.BlockNoteWebApp.controller;

import com.lider.BlockNoteWebApp.domain.Order;
import com.lider.BlockNoteWebApp.domain.OrderDetail;
import com.lider.BlockNoteWebApp.domain.User;
import com.lider.BlockNoteWebApp.repos.OrderDetailRepo;
import com.lider.BlockNoteWebApp.repos.OrderRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.math.BigInteger;
import java.util.List;
import java.util.Map;

@Controller
@RequestMapping("/cart") //чтобы в каждом методе отдельно не прописывать
public class CartController {

    @Autowired // This means to get the bean called ProductRepo
    // Which is auto-generated by Spring, we will use it to handle the data
    private OrderRepo OrderRepo;
    @Autowired
    private OrderDetailRepo OrderDetailRepo;

    @GetMapping
    public String cartView(
            @AuthenticationPrincipal User user,
            Map<String, Object> model
    ) {
        Order order = OrderRepo.findByCustomer(user);
        List<OrderDetail> orderDetails = OrderDetailRepo.findAllByOrder(order);

        model.put("order", order);
        model.put("orderdetails", orderDetails);

        return "cart";
    }

    @PostMapping
    public String updateCart(
            @AuthenticationPrincipal User user,
            @RequestParam BigInteger productId,
            @RequestParam(required = false, defaultValue = "-1") Integer count,
            Model model
    ) {
        if (count == -1) {//DELETE REQUEST
            updateOrder(productId,0, user, model);
//            OrderDetailRepo.deleteByProductId(productId);
            OrderDetail orderDetail = OrderDetailRepo.findByProductId(productId);
            OrderDetailRepo.delete(orderDetail);

            Order order = OrderRepo.findByCustomer(user);
            List<OrderDetail> orderDetails = OrderDetailRepo.findAllByOrder(order);
            model.addAttribute("order", order);
            model.addAttribute("orderdetails", orderDetails);
        }
        else {
            updateOrder(productId, count, user, model);
        }

        return "cart";
    }

    private void updateOrder(
            BigInteger productId,
            Integer count,
            User user,
            Model model
    ) {
        //Updating Order details
        OrderDetail productDetails = OrderDetailRepo.findByProductId(productId);

        productDetails.setQuanity(count);
        Integer prevProductAmount = productDetails.getAmount();
        Integer newProductAmount = count * productDetails.getPrice();
        productDetails.setAmount(newProductAmount);

        OrderDetailRepo.save(productDetails);

        //Updating OrderS
        Order order = OrderRepo.findByCustomer(user);
        Integer prevOrderAmount = order.getAmount();
        order.setAmount(prevOrderAmount - prevProductAmount + newProductAmount);

        OrderDetailRepo.save(productDetails);

        //Adding everything on th page
        List<OrderDetail> orderDetails = OrderDetailRepo.findAllByOrder(order);

        model.addAttribute("order", order);
        model.addAttribute("orderdetails", orderDetails);
    }

//    @DeleteMapping
//    public String removeOrderDetails(
//            @AuthenticationPrincipal User user,
//            @RequestParam BigInteger productId,
//            Model model
//    ) {
//        updateOrder(productId,0, user, model);
//        OrderDetailRepo.deleteByProductId(productId);
//
//        return "cart";
//    }
}
