package com.lider.BlockNoteWebApp.controller;

import com.lider.BlockNoteWebApp.domain.Product;
import com.lider.BlockNoteWebApp.repos.ProductRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletResponse;
import javax.websocket.server.PathParam;

@Controller
public class ProductController {

    @Autowired // This means to get the bean called ProductRepo
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepo ProductRepo;

    @GetMapping("/main/{productId}")
    public String main(
            @PathVariable("productId") String productId,
            Model model
    ) {
        Long id = Long.parseLong(productId);
        Product product = ProductRepo.findById(id);

        model.addAttribute("product", product);

        return "productDetails";
    }
}
